# permissions for end users to edit gitopsrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitopsrepo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kalypso-scheduler
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: gitopsrepo-editor-role
rules:
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/status
  verbs:
  - get
