---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - clustertypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/status
  verbs:
  - get
  - patch
  - update
