---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignmentpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignmentpackages/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignmentpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloadregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloadregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloadregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
