apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: workload
    app.kubernetes.io/instance: workload-sample
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kalypso-scheduler
  name: workload-sample
spec:
  # TODO(user): Add fields here
