apiVersion: scheduler.kalypso.io/v1alpha1
kind: DeploymentTarget
metadata:
  labels:
    app.kubernetes.io/name: deploymenttarget
    app.kubernetes.io/instance: deploymenttarget-sample
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kalypso-scheduler
    workspace: kaizen-app-team
    purpose: functional-test
    edge: "true"
    workload: hello-world-app
  name: hello-world-app-functional-test
spec:
  environment: dev
  manifests:
    repo: https://github.com/microsoft/kalypso-app-gitops
    branch: dev
    path: ./functional-test
