apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  labels:
    app.kubernetes.io/name: template
    app.kubernetes.io/instance: template-sample
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kalypso-scheduler
    someLabel: "false"
  name: arc-flux
spec:
  type: reconciler
  manifests:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: "{{ .DeploymentTargetName}}"
        namespace: flux-system
      spec:
        interval: 1m0s
        url: "{{ .Repo}}"
        ref:
          branch: "{{ .Branch}}"
        secretRef:
            name: repo-secret    
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: "{{ .DeploymentTargetName}}"
        namespace: flux-system
      spec:
        interval: 1m0s
        targetNamespace: "{{ .Namespace}}"
        sourceRef:
          kind: GitRepository
          name: "{{ .DeploymentTargetName}}"
        path: "{{ .Path}}" 
        prune: true
