{{ if .Values.ghRepoToken }}
apiVersion: v1
kind: Secret
metadata:
  name: gh-repo-secret
  namespace: flux-system
type: Opaque
data:
  password: {{ .Values.ghRepoToken | b64enc | quote}}
  username: {{ "kalypso" | b64enc | quote}}
{{ end }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: gh-repo-secret
type: Opaque
data:
  {{ if .Values.ghRepoToken }}
  token: {{ .Values.ghRepoToken  | b64enc | quote}}
  {{ else }}
  token: {{ "token" | b64enc | quote}}
  {{ end }}  
---  
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: control-plane
  namespace: flux-system
spec:
  interval: 10s
  ignore: |
    # exclude all
    /*
    # include .environments
    !/.environments 
  url: {{  required "Control Plane repo URL (controlPlaneURL) is required"  .Values.controlPlaneURL }}
  ref:
    branch: {{ required "Control Plane repo Branch (controlPlaneBranch) is required" .Values.controlPlaneBranch }}
{{ if .Values.ghRepoToken }}
  secretRef:
    name: gh-repo-secret
{{ end }}
---      
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: control-plane
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: {{ .Release.Namespace }}
  sourceRef:
    kind: GitRepository
    name: control-plane
  path: .environments
  prune: true
