apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kalypso-scheduler.fullname" . }}-manager-role
  labels:
  {{- include "kalypso-scheduler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - assignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/finalizers
  verbs:
  - update
- apiGroups:
  - scheduler.kalypso.io
  resources:
  - gitopsrepoes/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kalypso-scheduler.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kalypso-scheduler
    app.kubernetes.io/part-of: kalypso-scheduler
  {{- include "kalypso-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kalypso-scheduler.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kalypso-scheduler.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'