apiVersion: v1
kind: Service
metadata:
  name: {{ include "kalypso-scheduler.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kalypso-scheduler
    app.kubernetes.io/part-of: kalypso-scheduler
    control-plane: controller-manager
  {{- include "kalypso-scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "kalypso-scheduler.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}