controllerManager:
  # kubeRbacProxy has been removed as it's deprecated
  # Controller-runtime's WithAuthenticationAndAuthorization feature is now used instead
  manager:
    image:
      repository: kaizentm/kalypso
      tag: 1.0.1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https-metrics
  type: ClusterIP
